### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by M1hacka** [Infinidat/infi.clickhouse_orm#10]
Hey again, I've written a patch with Materialized and Alias fields, and ready to upload it. But this repo doesn't give me premission to create my own branches. Should I upload to develop? Or how can I gain permissions? Thanks.

**Comment by ishirav** [comment]
Thanks! I think you can create a pull request (there were a few from other people, so I assume you also have permission to create one)

**Comment by M1hacka** [comment]
I can't push my own branch (get 403 error). Should I upload to develop?

**Comment by ishirav** [comment]
Try following the instructions here to create a pull request: https://help.github.com/articles/creating-a-pull-request/

**Comment by ishirav** [comment]
And yes, use the develop branch and not master.

**Comment by M1hacka** [comment]
![screen](https://cloud.githubusercontent.com/assets/2315339/22328643/17ff04b6-e3df-11e6-8ad2-9282f0950d56.png)
I have no push access. So I can't upload my commits to develop or any other branch. So I can't create pull request from BranchA to BranchB.
How can I gain access?

**Comment by M1hacka** [comment]
Sorry for stupid questions, never contributed before =).
