### ISSUE TITLE
Use requests Session object for better performance

### ISSUE THREAD

**Issue by ishirav** [Infinidat/infi.clickhouse_orm#100]

**Comment by emakarov** [comment]
@ishirav you may consider switching to pycurl, it has faster performance than requests

**Comment by ishirav** [comment]
Thanks, I didn't know about pycurl. It looks very low-level and not programmer friendly, though: https://github.com/0xyd/Pycurl-vs-Requests
If I was planning to make such significant changes , it might make more sense to just switch to ClickHouse's native protocol.
For now I was just planning to use requests.Session, which is a trivial change but has significant performance gains.

**Comment by emakarov** [comment]
yes, it's more low-level, i.e. configuration of curl

for native protocol possible library is https://github.com/mymarilyn/clickhouse-driver

**Comment by emakarov** [comment]
basically in my project, I use clickhouse-driver for inserts and infi for different REST API and DB modelling now

**Comment by emakarov** [comment]
requests have also setting related to `proxy` (by default is enabled) which you can consider switching off (NO-PROXY), in addition, requests may sometimes perform significantly slower with hostnames instead of IP addresses
issues similar to this https://github.com/requests/requests/issues/879

**Comment by ishirav** [comment]
Fixed in v1.0.4
