### ISSUE TITLE
Don't use http authentication parameters

### ISSUE THREAD

**Issue by M1hacka** [Infinidat/infi.clickhouse_orm#105]
Hi.
It's not a good idea to pass authentication params in GET url. For instance, Sentry shows full url on error, and so all passwords are logged to Sentry. May be it's better to use basic auth? Described [here](https://clickhouse.yandex/docs/en/interfaces/http/)

**Comment by ishirav** [comment]
Fixed for the next release

**Comment by ishirav** [comment]
Fixed on v1.1.0
