### ISSUE TITLE
In clickhouse 19.3.3 error code is parsed incorrectly

### ISSUE THREAD

**Issue by M1hacka** [Infinidat/infi.clickhouse_orm#108]
After upgrading to clickhouse 19.3.3 from 19.1.1 ServerError is always returned with code=0.
I get 'Code: 60, e.displayText() = DB::Exception: Table test.django_clickhouse_migrations doesn\\'t exist.' message from clickhouse, which is not parsed by [regexp](https://github.com/Infinidat/infi.clickhouse_orm/blob/develop/src/infi/clickhouse_orm/database.py#L43)(it doesn't have `e.what`)

**Comment by iFoton** [comment]
I confirm that orm broken on 19.3.3/4. Can't make insertion.

**Comment by M1hacka** [comment]
@Foton, may be it's not infi bug in your case? See https://github.com/yandex/ClickHouse/issues/4431#issuecomment-465081618

**Comment by M1hacka** [comment]
P. s. My problem here is only invalid error code, not inserts broken

**Comment by iFoton** [comment]
Sorry, my bad, seems it CH bug.

**Comment by ishirav** [comment]
Fixed for the next release.

**Comment by ishirav** [comment]
Fixed on v1.1.0
