### ISSUE TITLE
Cannot SELECT WHERE has(field, value)

### ISSUE THREAD

**Issue by Chocorean** [Infinidat/infi.clickhouse_orm#121]
I need to do this kind of query:
```sql
SELECT * FROM table WHERE has(field, value)
```
`field` is an array of UInt8 and `value` is a number. There is currently no operator to do this and I don't find a quick fix.

EDIT: made myself a few lines for adding it but I would be great to see it in your code. :)

**Comment by M1hacka** [comment]
I suppose, it's related to https://github.com/Infinidat/infi.clickhouse_orm/issues/73

**Comment by Chocorean** [comment]
Dup of #73
