### ISSUE TITLE
Missing tags for 1.1.0 and 1.2.0 PyPI releases

### ISSUE THREAD

**Issue by Jamim** [Infinidat/infi.clickhouse_orm#135]
Hello,

I found that there are no tags for [1.1.0](https://pypi.org/project/infi.clickhouse_orm/1.1.0/) and [1.2.0](https://pypi.org/project/infi.clickhouse_orm/1.2.0/) releases in this repository.
Could you please push missing tags to this repo?

Thank you!

**Comment by ishirav** [comment]
Pushed, sorry about the delay.
