### ISSUE TITLE
Reading without a Model doesn't work with LowCardinality type

### ISSUE THREAD

**Issue by coonglinh** [Infinidat/infi.clickhouse_orm#137]
I have a table with LowCardinality(String) type.
Reading without a model is not work with this datatype:

- Function
`db.select('SELECT my_lowcardinality_string FROM my_table')`

- Error:
`
  File "/home/linh/.local/lib/python3.6/site-packages/infi/clickhouse_orm/models.py", line 94, in create_ad_hoc_field
    raise NotImplementedError('No field class for %s' % db_type)
NotImplementedError: No field class for LowCardinality(String)
`

Are you going to support it in the future ?

**Comment by ishirav** [comment]
Looks like a bug in the identification of the column type, I'll fix it.

**Comment by ishirav** [comment]
Fixed in v1.3.0
