### ISSUE TITLE
Lowercase of name table in objects_in.

### ISSUE THREAD

**Issue by vladimirteddy** [Infinidat/infi.clickhouse_orm#146]
I used ```qs = ThinkPad.objects_in(database)```. I ```print(qs)```, I saw my query is ```SELECT Id, Name, StockAge FROM thinkpad```. How can I use "ThinkPad" not "thinkpad"? Because my table in database is "ThinkPad".

**Comment by ishirav** [comment]
You can override the default table name like this:
```
class ThinkPad(Model):

    ...

    @classmethod
    def table_name(cls):
        return 'ThinkPad'
```

**Comment by vladimirteddy** [comment]
> You can override the default table name like this:
> 
> ```
> class ThinkPad(Model):
> 
>     ...
> 
>     @classmethod
>     def table_name(cls):
>         return 'ThinkPad'
> ```

Thank @ishirav
