### ISSUE TITLE
How can I use nested?

### ISSUE THREAD

**Issue by vladimirteddy** [Infinidat/infi.clickhouse_orm#149]
Doc in ClickHouse: https://clickhouse.tech/docs/en/sql-reference/data-types/nested-data-structures/nested/

**Comment by ishirav** [comment]
Hi, the ORM does not currently support nested structures.

**Comment by vladimirteddy** [comment]
Thank @ishirav :D. Aaaa... When will you support?

**Comment by ishirav** [comment]
I don't have any specific plans to do so at the moment, sorry.

**Comment by vladimirteddy** [comment]
Thank @ishirav.
