### ISSUE TITLE
Does this ORM have a support for External Dictionaries?

### ISSUE THREAD

**Issue by tirsky** [Infinidat/infi.clickhouse_orm#151]
I want to do requests, filtering, aggregating with external dict.

raw SQL:

`        select dictGetString('schema.table_in_postgres', 'field_in_postgres', tuple(id_in_clickhouse))`

Like this:

`Person.objects.filter(F.isIn(Person.dict_field = 1)) `or queryset `qs = qs.aggregate(Person.dict_field1, Person.dict_field2, ...)`

Now I'm using a simple hack:

1. Create 

```
FakeFieldClass(Model):
        dict_field = model.StringField()
```

2. Then I create a model class `Person(FakeFieldClass)`

3. And do it like this `queryset.filter(Person.dict_field)`

4. Then convert it to raw sql and replace dict_field with `select dictGetString('schema.table_in_postgres', 'field_in_postgres', tuple(id_in_clickhouse))` in python

5. Then do `data = clickhouse_db.select(query, Person)`

Profit11!

P.S. Of course I can do replacing in class, but for me `.replace` is better in code

**Comment by ishirav** [comment]
Hi,

I have to admit I haven't used external dictionaries yet, so my familiarity with them is limited. But to me it seems that you simply want the ORM to support all the `dictGet*` and `dictHas` functions. This would allow building queries such as:
```python
# Assuming we have an external dict containing Japanese names, find people with a Japanese last name
Person.objects_in(db).filter(F.dictHas('public.japanese_names', Person.last_name))

# Assuming we have an external dict mapping event_code to numeric severity, find events with severity > 3
Event.objects_in(db).filter(F.dictGet('public.event_codes', 'severity', Event.event_code) > 3)
```
Is this what you're trying to achieve?

**Comment by tirsky** [comment]
Yep, I think it will very useful)!

**Comment by ishirav** [comment]
Version 2.1.0 was released, which supports functions for working with dictionaries (`F.dict*`)
