### ISSUE TITLE
Python 2 Non-ASCII character '\xe2' in models.py

### ISSUE THREAD

**Issue by nevol1708** [Infinidat/infi.clickhouse_orm#156]
Traceback (most recent call last):
  File "libraries/ClickhouseORM.py", line 2, in <module>
    from infi.clickhouse_orm import Database
  File "/usr/local/lib/python2.7/dist-packages/infi/clickhouse_orm/__init__.py", line 3, in <module>
    from infi.clickhouse_orm.database import *
  File "/usr/local/lib/python2.7/dist-packages/infi/clickhouse_orm/database.py", line 6, in <module>
    from .models import ModelBase
  File "/usr/local/lib/python2.7/dist-packages/infi/clickhouse_orm/models.py", line 90
SyntaxError: Non-ASCII character '\xe2' in file /usr/local/lib/python2.7/dist-packages/infi/clickhouse_orm/models.py on line 91, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Problem in comment of code contains "-" is not support in python2

**Comment by ishirav** [comment]
Hi, as stated in the change log, version 2.0+ does not support Python 2.7 any more. If you want to use Python 2.7, please install version 1.4.0 of the ORM.
https://github.com/Infinidat/infi.clickhouse_orm/blob/develop/CHANGELOG.md

**Comment by nevol1708** [comment]
@ishirav another problem when use version 1.4.0 of the ORM, i'm install from pip but can not import infi.clickhouse_orm.funcs, it seem does not exist funcs file in library. Thank you for your help.

**Comment by ishirav** [comment]
That is true, many new features were added in v2, including the funcs mechanism. If you are using v1.4, please read the documentation that matches that version: https://github.com/Infinidat/infi.clickhouse_orm/tree/v1.4.0/docs
