### ISSUE TITLE
batch size

### ISSUE THREAD

**Issue by berghauz** [Infinidat/infi.clickhouse_orm#17]
Hi.
What reason in batch_size inside
def insert(self, model_instances, batch_size=1000) if it don't split whole request in batches actually?

**Comment by ishirav** [comment]
It does use the batch size - take a look at the gen() function inside insert().
One request is sent to the server for each batch of rows.

**Comment by berghauz** [comment]
Yes, it does split whole request to batches smaller or equal batch_size, but request.post do his work in one request, i.e. one batch which looks like list ['insert into ...','batch1','batch2','batch3']
What is purpose to use batch if it is not batching requests? Or I'm miss something.

**Comment by ishirav** [comment]
Ah yes, you are right. All of the data is sent in one request.
The batching was done for performance reasons - initially there were no batches, meaning that each row was encoded as TSV and immediately yielded by the generator. This meant that to insert a million rows, gen() was called a million times. This overhead made things pretty slow.
I added the batching, so now when inserting a million rows gen() is called only 1000 times, and this improved performance considerably.

**Comment by berghauz** [comment]
Damn, i miss that request support chunked transfer by generator objects.
Sorry, i catch the point :+1: 
But it not clarify, why you mention that gen() runs multiple times, it runs once at insert in self._send(gen())

**Comment by ishirav** [comment]
gen() is called once,  but it returns a generator. The generator is passed to _send, and then requests call next() repeatedly to get the next chunk of data. I profiled a benchmark that inserts millions of rows, and these calls to next() had a significant overhead. Reducing their numbers by batching rows improved the performance of insert(). But if you don't want to use it, you can pass batch_size=1.
