### ISSUE TITLE
Is it possible to create MATERIALIZED fields?

### ISSUE THREAD

**Issue by hunty** [Infinidat/infi.clickhouse_orm#18]
Is it possible to create MATERIAL fields like `"createdDate MATERIAL toDate(createdAt)"`?
In docs I can find only how to create simple fields with defined types but not expressions.
How I can describe it in model?
I need such structure:
```
CREATE TABLE subscriptions
   (
       Date DateTime,
       Email String,
       ListId Int32,
       ListName String,
       DateKey Date MATERIALIZED toDate(Date)
   ) ENGINE = MergeTree(DateKey, (Date, Email, ListId), 8192)
```

**Comment by srgkm** [comment]
Yes, you can https://github.com/Infinidat/infi.clickhouse_orm#working-with-materialized-and-alias-fields
