### ISSUE TITLE
Issue while using with Altinity clickhouse enterprise version

### ISSUE THREAD

**Issue by Jatinbalodhi96** [Infinidat/infi.clickhouse_orm#182]
https://github.com/Infinidat/infi.clickhouse_orm/blob/76d432b838953fb7f762a9fe55fd94ce47520f01/src/infi/clickhouse_orm/database.py#L416

In the opensource clickhouse version, we get version value as `21.3.15.4`

But in Altinity clickhouse version we get version value as `21.3.15.4.altinity+stable`
which gives an error because there are alphabets on this version

Can someone suggest a global solution for this problem

**Comment by sinmaker** [comment]
Resolved
