### ISSUE TITLE
Native format and simple mapping

### ISSUE THREAD

**Issue by hunty** [Infinidat/infi.clickhouse_orm#20]
Using TabSeparatedWithNames format is slower than using Native.
Is it any way to use it?
Also, I don't need sometimes to use models to fetch data. Just get some collection of str or int
Is it possible?

**Comment by ishirav** [comment]
Hi,

The documentation states about Native that "It doesn't make sense to work with this format yourself". 
Furthermore, it doesn't returns data in rows, making features such as pagination very difficult to implement.

Re models: if you don't specify a model_class in Database.select(), an ad-hoc model will be created according to the column definitions returned by the query. This also means that the values will be converted to their Pythonic types.

If you don't even need this, you can use Database.raw() to get the query result as text. Then you could iterate over the lines in the text and call utils.parse_tsv() to convert each line into a list of string values.

**Comment by hunty** [comment]
Thanks a lot! It helps.
