### ISSUE TITLE
Bulk import parsing fails

### ISSUE THREAD

**Issue by M1hacka** [Infinidat/infi.clickhouse_orm#25]
I'm trying importing multiple data rows into clickhouse. And it is failing with the following error:
```
infi.clickhouse_orm.database.DatabaseException: Code: 27, e.displayText() = DB::Exception: Cannot parse input: expected \t before: \n0\t52\t1490853195\t1490854241\t471\t1115\t8\t1490854107\t1490854194\t1490854194\t3392\t1\n0\t53\t1490854114\t1490854241\t471\t1116\t8\t1490854114\t1490854183\t1490854186\t3388\t1\n0\t5: (at row 51)

Row 50:
Column 0,   name: _version,               type: UInt8,    parsed text: "0"
Column 1,   name: id,                     type: UInt64,   parsed text: "50"
Column 2,   name: created,                type: DateTime, parsed text: "1490790250"
Column 3,   name: closed,                 type: DateTime, parsed text: "0"
Column 4,   name: user_id,                type: UInt64,   parsed text: "367"
Column 5,   name: conversation_id,        type: UInt64,   parsed text: "1114"
Column 6,   name: app_id,                 type: UInt64,   parsed text: "8"
Column 7,   name: first_user_reply_time,  type: DateTime, parsed text: "0"
Column 8,   name: admin_answer_time,      type: DateTime, parsed text: "0"
Column 9,   name: admin_last_answer_time, type: DateTime, parsed text: "1490790250"
Column 10,  name: admin_last_answer_id,   type: UInt64,   parsed text: "3362"
Column 11,  name: sign,                   type: Int8,     parsed text: "1"

Row 51:
Column 0,   name: _version,               type: UInt8,    parsed text: "0"
Column 1,   name: id,                     type: UInt64,   parsed text: "51"
Column 2,   name: created,                type: DateTime, parsed text: "1490791652"
Column 3,   name: closed,                 type: DateTime, parsed text: "0<TAB>11<TAB>13<TAB>1<TAB>0<TAB>0<TAB>0<TAB>0<TAB>1"
ERROR: Line feed found where tab is expected. It's like your file has less columns than expected.
And if your file have right number of columns, maybe it have unescaped backslash in value before tab, which cause tab has escaped.

, e.what() = DB::Exception
```
Here are rows 50-52 from my PostgreSQL database:
![screen](https://cloud.githubusercontent.com/assets/2315339/24490536/6cb786b6-153c-11e7-8392-d891dcb4a8d5.png)

**Comment by ishirav** [comment]
Perhaps it's related to this? 
https://github.com/Infinidat/infi.clickhouse_orm/pull/24
At some recent version, ClickHouse stopped accepting "0" for datetime. It now expects "0000000000".

**Comment by M1hacka** [comment]
May be. It's strange but as you see there was no failing on row 50, which also contained 0 values.

**Comment by ishirav** [comment]
Yes, that's strange. You can try patching your copy of the ORM and print the result of to_tsv() (in models.py), so you'll see exactly what's being sent to ClickHouse. Or sniff the network...

**Comment by M1hacka** [comment]
I've installed nikepan version of ORM and my bug is still reproduced.
I'll comment to_tsv output soon.

**Comment by M1hacka** [comment]
It's a pitty, but test data on which import failed was deleted during testing process. I've tried to reproduce the bug, but I can't. I'll write here if I do.

**Comment by nikepan** [comment]
This strange, because I always use bulk add records. And this error related to fix in my pull request. Maybe you not complete install source first time, and next time code updated then everything  became good?

**Comment by M1hacka** [comment]
It's very strange, but yesterday we commited this on production servers (it couldn't kill anything, new functionality only) and everything went ok, 65 million records were imported successfully. The ORM was installed by "pip install -U infi.clickhouse-orm" command (not your branch). There are NULL date values in source database - no problems were found. Strange bug, I'll report if I reproduce it.
