### ISSUE TITLE
Very long inserts and MemoryError

### ISSUE THREAD

**Issue by M1hacka** [Infinidat/infi.clickhouse_orm#26]
Bulk inserts work very slow via ORM.
I insert 1k of rows into table. Here is the time measure of code:
```
t2 = time.time()
statsd.timing(statsd_key_prefix + '.import_clickhouse_model_objects.convert', t2 - t1)

for model_group in convert_items.values():
     settings.CLICKHOUSE_DB.insert(model_group, batch_size=batch_size)
t3 = time.time()
```
I know, that `convert_items `dict contains only 1 item. So, in fact, only insert is measured.
batch_size is 1000 here. There are 1000 elements in the list.
I've also tried making batch_size=10000, but the query failed with MemoryError on backend size...

ClickHouse server is not loaded at all (8 cores, 16gb memory). htop doesn't show any activity practically.

Here is the graph, where you can see inserts are executed 60-100 seconds... Very very slow.
![screenshot](https://cloud.githubusercontent.com/assets/2315339/24703337/43e4b60c-1a1c-11e7-8526-6fcfc872a6b3.png)

Another query in my code makes insert from select via `settings.CLICKHOUSE_DB.raw(query)`. It inserts 200 rows and executes for 1-2 seconds only

**Comment by M1hacka** [comment]
A little bit about connected MemoryError.
I tipically catch it here:
![screenshot 2](https://cloud.githubusercontent.com/assets/2315339/24703667/99fe0894-1a1d-11e7-8a17-090a2558b700.png)
It occures on big batches of data only (more than 200, this number is heuristic.

**Comment by ishirav** [comment]
Do you have a way to run this with a profiler and post the results?
Perhaps using https://pypi.python.org/pypi/profilehooks

**Comment by M1hacka** [comment]
![screen](https://cloud.githubusercontent.com/assets/2315339/24704730/4aa88be8-1a22-11e7-98b9-2aa6db97a6ea.png)

**Comment by ishirav** [comment]
Wow... So there are 335 million calls to dict.get, but only 1900 calls to join. And yet the join takes ages. Do you have extremely long data rows? E.g. a very large number of columns or a small number of very long values?

**Comment by M1hacka** [comment]
Suppose the problem is in 
`value = "".join(SPECIAL_CHARS.get(c, c) for c in value)` (utils.py 28). It is called too 300 mln times symbol by symbol. Suppose it's much better to use regular expressions here.
[re.sub](https://docs.python.org/2/library/re.html#re.sub)
```
value = re.sub(r"([\b\f\r\n\t\0])", "\\\\\\1", value)
value = re.sub(r"(['\\])", "\\\\\\\\\\1", value)
```

**Comment by M1hacka** [comment]
![screen](https://cloud.githubusercontent.com/assets/2315339/24705696/83d2210a-1a26-11e7-99c4-aacd11d9de0c.png)
Here is the table
As I've said, I insert 1000 rows of data

**Comment by M1hacka** [comment]
Body may be a very big part - email html for example

**Comment by ishirav** [comment]
Could you try patching the implementation of utils.escape as you suggested, and testing to see if it helps? 

I did not profile on very large texts so I guess in your use-case this is indeed inefficient.
I will do some testing with large text values, perhaps it would be better to use cStringIO to build the batches in Database.insert instead of joining arrays.

**Comment by M1hacka** [comment]
Suppose, yes. I'll write the results here.

**Comment by ishirav** [comment]
BTW I don't think the regular expressions you wrote above are correct, but perhaps I'm missing something.

**Comment by ishirav** [comment]
I think this should work:

    def escape_one(match):
        return SPECIAL_CHARS[match.group(0)]

    def escape(value, quote=True):
        if isinstance(value, string_types):
            value = SPECIAL_CHARS_REGEX.sub(escape_one, value)
            if quote:
                value = "'" + value + "'"
        return text_type(value)

**Comment by M1hacka** [comment]
yeh, right

**Comment by ishirav** [comment]
I tested the old vs. new implementation of utils.escape on large texts, and the difference is huge. I'm committing the change (to the develop branch).
Thanks!

**Comment by ishirav** [comment]
I released v0.8.1 with this fix and a few other performance improvements. It would be interesting to see the difference in performance on your use-case.

**Comment by M1hacka** [comment]
Thanks, I'll test it tomorrow

**Comment by M1hacka** [comment]
![screen](https://cloud.githubusercontent.com/assets/2315339/24740028/85f6e3c0-1ab8-11e7-9047-f5cd3eb89c85.png)
Awesome

**Comment by M1hacka** [comment]
![image](https://cloud.githubusercontent.com/assets/2315339/24740698/f8598014-1abb-11e7-87bf-aab7dc7ea30b.png)
Less than a second =) Great work
