### ISSUE TITLE
FixedString field

### ISSUE THREAD

**Issue by kszucs** [Infinidat/infi.clickhouse_orm#30]
Would You please provide a field for FixedString type?

```python
NotImplementedError: No field class for FixedString(7)
```

**Comment by ishirav** [comment]
Yes, I'll add support for FixedString.

**Comment by kszucs** [comment]
That was quick :) Thanks!

**Comment by ishirav** [comment]
@kszucs, what do you think: when reading the FixedString from the database, it gets padded with null bytes. Should the ORM remove these nulls, returning the "clean" string?

**Comment by kszucs** [comment]
I'm voting for the cleaned version.

**Comment by kszucs** [comment]
How can I install the develop branch? Just create a release with projector?

**Comment by ishirav** [comment]
If you already ran "projector devenv build", you should see a setup.py file under the project's folder.
So you just need to run "python setup.py install"

**Comment by ishirav** [comment]
Version 0.9.0 was released with support for FixedString.
