### ISSUE TITLE
Pandas interface

### ISSUE THREAD

**Issue by kszucs** [Infinidat/infi.clickhouse_orm#31]
Any chance to implement a pandas connector?
Afterwards I intend to use with dask distributed, see issue https://github.com/dask/distributed/issues/337

**Comment by ishirav** [comment]
I'm don't have any experience with pandas, so can you please elaborate on what exactly needs to be implemented?

**Comment by kszucs** [comment]
Sure! cc @frol 

I suggest You to http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html get a general overview.
Here are a couple of methods for sql, You can have a general overview for the interface:

http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_sql.html
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_sql_query.html#pandas.read_sql_query
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_sql_table.html#pandas.read_sql_table
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_sql.html#pandas.DataFrame.to_sql

Something similar would be nice, like:

```python
df = read_clickhouse_table(table, db)
df = read_clickhouse(query, db)

to_clickhouse(df)
```

Where `query` could be a string sql expression or a `QuerySet` instance.
Pandas nicely works with pure python structures (csv, tsv, list, json), also support multiple orients.

When writing a pandas dataframe to clickhouse, something like ad_hoc_model for querying would be nice. The following properties describe the pandas dataframe metadata. We need a type mapping from dtypes to clickhouse types.
```python
df.index
df.columns
df.dtypes
```

**Comment by kszucs** [comment]
Something like this:

```python
from infi.clickhouse_orm.models import ModelBase, Model
from toolz import valmap


mapping = {'object': 'String',
           'uint64': 'UInt64',
           'uint32': 'UInt32',
           'uint16': 'UInt16',
           'uint8': 'UInt8',
           'int64': 'Int64',
           'int32': 'Int32',
           'int16': 'Int16',
           'int8': 'Int8',
           'bool': 'UInt8',
           'datetime64[D]': 'Date',
           'datetime64[ns]': 'DateTime'}

MAPPING = {np.dtype(k): v for k, v in mapping.items()}


def pandas_model(df, table, date):
    @classmethod
    def table_name(cls):
        return table
    
    indexes = [(name, df.index.dtype) for name in df.index.names]
    columns = list(df.dtypes.items())
    fields = {column: MAPPING[dtype] for column, dtype in indexes + columns}
    fields[date] = 'Date'
    
    attrs = valmap(ModelBase.create_ad_hoc_field, fields)

    model = ModelBase.__new__(ModelBase, 'PandasModel', (Model,), attrs)
    model.engine = MergeTree(date, tuple(df.index.names))
    model.table_name = table_name

    return model
```

**Comment by emakarov** [comment]
my 2c here - 
For me connection to pandas is not seems like a task for ORM, which in other frameworks usually is an agnostic to any external app. 
IMHO pandas connector looks like a good idea for another app, which can combine infi.clickhouse_orm and pandas.

**Comment by kszucs** [comment]
Fair enough. I guess I'll create as a separate package.

**Comment by ishirav** [comment]
I also tend to agree that it should be a separate project.
Seems like you already have the code fleshed out :)

One thing to keep in mind is that changes in future versions of the ORM might break the pandas package, so it would be prudent to test the new package against a specific version of the ORM, document which version was tested, and add that specific version as a dependency.

For example if you use requirements.txt, don't write:
`infi.clickhouse_orm`
`clickhouse_pandas`

Instead, refer to a specific version that is known to be compatible:
`infi.clickhouse_orm==0.8.1`
`clickhouse_pandas`
