### ISSUE TITLE
how to create and query data that save in  ENGINE is Distributed?

### ISSUE THREAD

**Issue by qietingfengling** [Infinidat/infi.clickhouse_orm#35]
hello, how to create and query data that save in  ENGINE is Distributed?

**Comment by ishirav** [comment]
Hi, I'm not sure if this is what you're asking but if you want to create a replicated engine, all you have to do is add two parameters when creating the engine: replica_table_path and replica_name. This works for any engine in the "merge tree" family.
See https://github.com/Infinidat/infi.clickhouse_orm/blob/develop/docs/table_engines.md#data-replication
