### ISSUE TITLE
Why CREATE DATABASE on connect?

### ISSUE THREAD

**Issue by RichRadics** [Infinidat/infi.clickhouse_orm#39]
It seems strange to automatically try to create a database if it doesn't exist, instead of throwing an error. I have had to clean up misspelt empty databases from ClickHouse after users have got names slightly wrong... Is there a particular core reason for doing this, or could it be changed to not do this in future?

**Comment by ishirav** [comment]
There are two reasons to try creating the database:

1. Simpler to use - you can just instantiate a Database object and start working with it.
2. It's a way to test that you can connect to ClickHouse and perform operations. So in case you can't, you'll get an error immediately.

I do understand that in some cases you would prefer not to do that, so perhaps we can add a flag to the initializer - something like this:
```
db = Database('my_db', autocreate=False)
```

**Comment by ishirav** [comment]
In version 0.9.2 you can instantiate a database with `autocreate=False`
