### ISSUE TITLE
batch insert

### ISSUE THREAD

**Issue by fengyuncrawl** [Infinidat/infi.clickhouse_orm#4]
When I use Python client to batch insert 10 million data into stand-alone clickhouse, The time spent avg 16min,why so slowly? Compared to use clickhouse-client spent avg 30 secs.

create table（id Int64,name String,open_time Date）MergeTree('open_time', ('id','name'))
when I use python client insert list to DB （for example: db.insert([p1,p2,p3...])）

**Comment by ishirav** [comment]
That's a good question, perhaps it's caused by the validation and type conversion that the ORM performs. Or perhaps 10 million rows take up a large amount of memory and cause swapping. Does it make a difference if you split the data into chunks of 10,000 rows each?
