### ISSUE TITLE
Add support "distinct"

### ISSUE THREAD

**Issue by ckcnik** [Infinidat/infi.clickhouse_orm#48]
The query does not work:
`gsm_count = ScanningNemo.objects_in(self.db).filter(project_id=self.project.id). \
                distinct('arfcn').count()`
Error text:
`QuerySet' object has no attribute 'distinct'`

**Comment by ckcnik** [comment]
I did it, but it's not very nice
`gsm_count = ScanningNemo.objects_in(self.db).filter(project_id=self.project.id). \
                only('arfcn').aggregate(ct='countDistinct(arfcn)').as_sql()`

**Comment by ishirav** [comment]
Support was added in v0.9.7
