### ISSUE TITLE
Support operator "Limit"

### ISSUE THREAD

**Issue by ckcnik** [Infinidat/infi.clickhouse_orm#53]
I want to do this
`first_obj_voice_call = VoiceCallSessionNemo.objects_in(db).\
                        filter(project_id=self.id).order_by('start_time').only('start_time').limit(1)`
but i getting an error
`'QuerySet' object has no attribute 'limit'`

**Comment by ishirav** [comment]
You can use slicing to get the same effect, see https://github.com/Infinidat/infi.clickhouse_orm/blob/develop/docs/querysets.md#slicing
