### ISSUE TITLE
Filtering null values support

### ISSUE THREAD

**Issue by kalombos** [Infinidat/infi.clickhouse_orm#71]
Hello, I didn't find the way how to implement this query:

```
SELECT *
FROM units 
WHERE isNull(parent)
```

Units.objects_in(ch_models.db).filter(parent=None) raises an error

**Comment by ishirav** [comment]
That's a good solution, if you could make it into a pull request (along with a test or two) I'd appreciate it.
You probably want the "ne" operator to behave in a similar manner.

**Comment by kalombos** [comment]
> if you could make it into a pull request (along with a test or two) I'd appreciate it.

Sure, i think i can make it a bit later

**Comment by ishirav** [comment]
Fixed in v1.0.2
