### ISSUE TITLE
QuerySet count() ignores slicing and ordering

### ISSUE THREAD

**Issue by M1hacka** [Infinidat/infi.clickhouse_orm#79]
Hi.
I've found a bug in QuerySets, it looks like it fully ignores slices and ordering when I do count().
I've found a hacky solution, adding distinct() to qs, which makes it doing a subquery, but that looks strange =)
```python
qs = MyModel.objects_in(settings.CLICKHOUSE_DB).order_by('created')[100:200]
print(qs.count())
# returns 59, but correct is 0

qs = qs.distinct()
print(qs.count())
# returns 0
```

**Comment by ishirav** [comment]
Fixed in v1.0.3
