### ISSUE TITLE
Is it possible to fetch columns of data ?

### ISSUE THREAD

**Issue by healiseu** [Infinidat/infi.clickhouse_orm#83]
Hi, I want to fetch columns of data, i.e. not to transform the rows you normally fetch from the server to columns. How is that possible with your ORM client ?  Let me give you an example with [clickhouse-driver][2] 

#### Row Format
`client.execute('select * from Floats limit 5')`
```python
Out[6]: 
[(0, 288542, 2000.013427734375),
 (1, 355625, 2000.032958984375),
 (2, 27808, 2000.0435791015625),
 (3, 220464, 2000.0506591796875),
 (4, 279648, 2000.060546875)]
```
#### Column Format
`client.execute('select * from Floats limit 5', columnar=True)`
```python
[(0, 1, 2, 3, 4),
 (288542, 355625, 27808, 220464, 279648),
 (2000.013427734375,
  2000.032958984375,
  2000.0435791015625,
  2000.0506591796875,
  2000.060546875)]
```

According to Clickhouse documentation on the [Native input and output format][1] you can read blocks in binary format. This format is columnar, i.e. I do not want to convert columns to rows and then back to columns again. 

I tried 
```python
from infi.clickhouse_orm.database import Database

db = Database('default')

for obj in db.select('select * from Floats limit 3 format Native'): print(obj)
```

But I got a ServerError
ServerError: Syntax error: failed at position 37: Native FORMAT TabSeparatedWithNamesAndTypes. Expected identifier (62)

It looks like infini-orm is trying to use the [TabSeparatedWithNamesAndTypes][3] format instead of the Native one I specified inside the query string.

So, is that possible with the current release and if not can you add this feature ? 
That will be great.

[1]: https://clickhouse.yandex/docs/en/interfaces/formats/#native
[2]: https://github.com/mymarilyn/clickhouse-driver#miscellaneous
[3]: https://clickhouse.yandex/docs/en/interfaces/formats/#tabseparatedwithnamesandtypes

**Comment by ishirav** [comment]
Please see my reply about the Native format in issue #82 .
It is not possible to fetch data in columns, because the whole premise behind ORMs is the conversion of database rows into objects.
For efficiency it is possible to load only specific columns from the database, and ignore all the rest. See https://github.com/Infinidat/infi.clickhouse_orm/blob/develop/docs/querysets.md#omitting-fields
