### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by M1hacka** [Infinidat/infi.clickhouse_orm#9]
Hey
I want to add Alias and Materizlized field types to the project.
I've installed everything, written in "Development" docs section. Now I'm trying to run tests with:
`bin/nosetests`
And receive:
```
Ran 0 tests in 0.000s
OK
```
May be I missed something? Why 0 tests?
Why can't i run them simply by using unittest?
Thanks.

**Comment by ishirav** [comment]
Hi,

Looks like the instructions in the README are correct. Just tried doing this and it ran the tests:

```
cd /tmp
git clone https://github.com/Infinidat/infi.clickhouse_orm.git
cd infi.clickhouse_orm
projector devenv build
bin/nosetests

```

Please make sure that you're in the infi.clickhouse_orm directory - perhaps you changed the directory to bin ?

**Comment by M1hacka** [comment]
Surely, I do. If I were in `bin/` , `bin/nosettests` wouldn't start... It started, but didn't find any tests.
Just Ctrl+C Ctrl+V your script => works.
If I clone repo into /vagrant folder => not 
works (no any errors occured).
May be some permission problems with Vagrant shared dir?
![screen](https://cloud.githubusercontent.com/assets/2315339/22292372/a8b42846-e32c-11e6-8ce3-c5006421ac09.png)

**Comment by ishirav** [comment]
I've never used Vagrant, so I don't have anything useful to contribute...

**Comment by M1hacka** [comment]
Futher investigation showed, that tests are only ran when test_x.py file have now executable permission.
Vagrant gives that permission by default => tests fail. chmod 644 solves the problem

**Comment by ishirav** [comment]
Interesting... thanks for the update.
