### ISSUE TITLE
How to check whether a select query returns empty?

### ISSUE THREAD

**Issue by q0987** [Infinidat/infi.clickhouse_orm#90]
`res = db.select("select distinct(partition) from system.parts where name='not_exist'")`

Question> How to check whether res contains empty query results?

Thank you

**Comment by M1hacka** [comment]
`res` will be a generator object. So you can simply convert it to list, and check if it is empty:
```python
list(db.select('SELECT 1 WHERE 0'))
# []
bool(list(db.select('SELECT * WHERE 0')))
# False
bool(list(db.select('SELECT1')))
# True
```

If you want to work with `system.parts` table there is special model to work with it:
```python
from infi.clickhouse_orm import SystemPart
list(SystemPart.get(db, conditions="name='not_exist')")
```

Firstly I wanted to suggest you use QuerySet with SystemPart:
```python
from infi.clickhouse_orm import SystemPart
bool(SystemPart.objects_in(db).filter(name='not_exist'))
# False
bool(SystemPart.objects_in(db).filter(name='exist'))
# True
```
But it seems there is a bug there. I created a separate issue for it: https://github.com/Infinidat/infi.clickhouse_orm/issues/98
