### ISSUE TITLE
FINAL

### ISSUE THREAD

**Issue by noisywiz** [Infinidat/infi.clickhouse_orm#92]
It would be great if the ORM supported FINAL modifier (CollapsingMergeTree, ReplacingMergeTree) https://clickhouse.yandex/docs/en/query_language/select/

**Comment by M1hacka** [comment]
Created a [PR](https://github.com/Infinidat/infi.clickhouse_orm/pull/94)

**Comment by M1hacka** [comment]
It's logical, but I see "The FINAL modifier can be used only for a SELECT from a CollapsingMergeTree table. " In the docs posted above

**Comment by ishirav** [comment]
Fixed in v1.0.4
