### ISSUE TITLE
Tests fail on python 3.6

### ISSUE THREAD

**Issue by M1hacka** [Infinidat/infi.clickhouse_orm#93]
Hi.
I've tried running tests on Python 3.6.5.
Calling `bin/nosetests` raises error:
```
Traceback (most recent call last):
  File "bin/nosetests", line 47, in <module>
    import nose
  File "/projects/venvs/venv36/lib/python3.6/site-packages/nose/__init__.py", line 1, in <module>
    from nose.core import collector, main, run, run_exit, runmodule
  File "/projects/venvs/venv36/lib/python3.6/site-packages/nose/core.py", line 5, in <module>
    import logging
  File "/usr/lib/python3.6/logging/__init__.py", line 26, in <module>
    import sys, os, time, io, traceback, warnings, weakref, collections
  File "/usr/lib/python3.6/traceback.py", line 5, in <module>
    import linecache
  File "/projects/venvs/venv36/lib/python3.6/linecache.py", line 11, in <module>
    import tokenize
  File "/projects/venvs/venv36/lib/python3.6/tokenize.py", line 33, in <module>
    import re
  File "/projects/venvs/venv36/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
```
According to [this](https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag) flow, it means enum has been redeclared.
I've found `join(base, 'eggs/enum34-1.1.6-py3.6.egg')` in `bin/nosetests` file. 
Commenting this line makes tests run fine. But I get:
```
(venv36) ubuntu@ubuntu-xenial:/projects/infi.clickhouse_orm$ bin/nosetests 

----------------------------------------------------------------------
Ran 0 tests in 0.850s

OK
```
My questions are:
1) Is enum34 library really needed? As it's causing a problem on last python versions
2) What is wrong with tests running?
Thanks.

**Comment by ishirav** [comment]
enum34 is needed to support enums in python versions older than 3.4, so we can't remove it.
Seems like it's a known issue: https://bitbucket.org/stoneleaf/enum34/issues/21/setuppy-should-no-op-for-python-34
There's a link there to stackoverflow with a possible solution, I'll see if there's a way to do that (it may require changes in infi.projector, our build tool).

As for the tests, can you try telling nose where to looks for them, e.g. `bin/nosetests tests/`

**Comment by M1hacka** [comment]
> As for the tests, can you try telling nose where to looks for them, e.g. `bin/nosetests tests/`
Nothing has changed, still 0 tests

**Comment by ishirav** [comment]
Strange. Can you list the commands you used for setting up the virtualenv?

**Comment by M1hacka** [comment]
It's a long time since it has been created, but I can try recreate it to have test results clean

**Comment by M1hacka** [comment]
```
sudo apt-get install virtualenv
virtualenv venv -p python3.6
source venv/bin/activate
easy_install -U infi.projector
cd /projects/infi.clickhouse_orm
projector devenv build
python setup.py install
bin/nosetests tests/
```
Still same result.

**Comment by M1hacka** [comment]
Same results for both 0 tests and enum34 problem in venvs for python 3.5 and 3.4.4

**Comment by M1hacka** [comment]
Works if I run `bin/nosetests tests.test_engines`
Doesn't work:
* `bin/nosetests tests`
* `bin/nosetests`

**Comment by ishirav** [comment]
Just to clarify, infi.clickhouse_orm works with Python 3 (all tests pass under 3.5 and 3.7).

To solve the enum34 problem, I replaced enum34 with enum-compat which ensures that enum34 will get installed only under Python 2.7, and not under Python 3.

**Comment by M1hacka** [comment]
It's a long time, I haven't tried it. I'll check this week

**Comment by ishirav** [comment]
Obsolete
